# Generated by Skyramp v1.3.16 on 2026-03-30 02:54:29.998397291 +0000 UTC m=+453.254061839
# Command: skyramp generate contract rest http://localhost:8000/api/v1/products \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output get_products_contract_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/products GET
def test_v_1_products_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_v1_products_GET_response_body = r'''[
        {
            "category": "Toys",
            "created_at": "2025-02-25T10:54:22-05:00",
            "description": "Bear Soft Toy",
            "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
            "in_stock": true,
            "name": "bigbear",
            "price": 9.99,
            "product_id": 1,
            "updated_at": "2025-02-25T10:54:22-05:00"
        }
    ]'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/products",
        method="GET",
        status_code=200,
        response_body=expected_v1_products_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    v1_products_GET_response = client.send_request(
        url=URL,
        path="/api/v1/products",
        method="GET",
        headers=headers,
        query_params={
            "limit": 10,
            "offset": 0,
            "order": "asc",
            "orderBy": None
        }
    )

    # Generated Assertions
    assert v1_products_GET_response.status_code == 200
    assert skyramp.check_schema(v1_products_GET_response, expected_v1_products_GET_response_body)
    assert skyramp.get_response_value(v1_products_GET_response, "0.category") is not None
    assert skyramp.get_response_value(v1_products_GET_response, "0.created_at") is not None
    assert skyramp.get_response_value(v1_products_GET_response, "0.description") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_v_1_products_get()
