# Generated by Skyramp v1.3.16 on 2026-03-28 23:46:56.657698909 +0000 UTC m=+248.857663732
# Command: skyramp generate contract rest http://localhost:8000/api/v1/orders \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output orders_contract_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python \
# 		--overwrite \
# 		--provider \
# 		--request-data {"customer_email":"test@example.com","items":[{"quantity":1,"product_id":1}]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/orders POST
def test_orders_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "test@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 1
            }
        ]
    }'''

    # Expected Response Body
    expected_orders_POST_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "abc@mail.com",
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "pending",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.check_schema(orders_POST_response, expected_orders_POST_response_body)
    assert skyramp.get_response_value(orders_POST_response, "created_at") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") is not None
    assert skyramp.get_response_value(orders_POST_response, "items.0.order_item_id") is not None
    assert skyramp.get_response_value(orders_POST_response, "order_id") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") == "test@example.com"
    assert skyramp.get_response_value(orders_POST_response, "status") == "pending"
    assert skyramp.get_response_value(orders_POST_response, "total_amount") >= 0


if __name__ == "__main__":
    test_orders_post()
