# Generated by Skyramp v1.3.16 on 2026-03-29 03:16:57.292043089 +0000 UTC m=+178.955062984
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output orders_products_cascade_delete_integration_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python/scenario_orders-products-cascade-delete.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    products_POST_request_body = r'''{
        "category": "Toys",
        "description": "Test product for cascade delete test",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "TestProduct",
        "price": 19.99
    }'''
    
    # Execute Request
    products_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.get_response_value(products_POST_response, "product_id") is not None
    assert skyramp.get_response_value(products_POST_response, "name") == "TestProduct"
    assert skyramp.get_response_value(products_POST_response, "price") == 19.99

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "cascade@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 1
            }
        ]
    }'''
    
    # Execute Request
    orders_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers,
        data_override={"items.0.product_id": skyramp.get_response_value(products_POST_response, "product_id")}
    )
    # Generated Assertions
    assert orders_POST_response.status_code == 201
    assert skyramp.get_response_value(orders_POST_response, "order_id") is not None
    assert skyramp.get_response_value(orders_POST_response, "customer_email") == "cascade@example.com"
    assert skyramp.get_response_value(orders_POST_response, "status") == "pending"
    assert skyramp.get_response_value(orders_POST_response, "total_amount") >= 0

    # Execute Request
    orders_orders_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/orders/{orders}",
        method="DELETE",
        headers=headers,
        path_params={"orders": skyramp.get_response_value(orders_POST_response, "order_id")}
    )
    # Generated Assertions
    assert orders_orders_DELETE_response.status_code == 200
    assert skyramp.get_response_value(orders_orders_DELETE_response, "message") == "Order cancelled successfully"

    # Execute Request
    products_products_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/products/{products}",
        method="GET",
        headers=headers,
        path_params={"products": skyramp.get_response_value(products_POST_response, "product_id")}
    )
    # Generated Assertions
    assert products_products_GET_response.status_code == 200
    assert skyramp.get_response_value(products_products_GET_response, "product_id") == skyramp.get_response_value(products_POST_response, "product_id")
    assert skyramp.get_response_value(products_products_GET_response, "name") == "TestProduct"
    assert skyramp.get_response_value(products_products_GET_response, "price") == 19.99


if __name__ == "__main__":
    test_integration()
