# Generated by Skyramp v1.3.16 on 2026-03-29 16:18:49.753671833 +0000 UTC m=+86.248756537
# Command: skyramp generate contract rest http://localhost:8000/api/v1/products \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output products_contract_reject_below_minimum_price_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python \
# 		--overwrite \
# 		--request-data {"category":"Toys","description":"Cheap Toy","image_url":"https://example.com/toy.jpg","in_stock":true,"name":"cheapitem","price":0.50} \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/products POST
def test_v_1_products_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    v1_products_POST_request_body = r'''{
        "category": "Toys",
        "description": "Cheap Toy",
        "image_url": "https://example.com/toy.jpg",
        "in_stock": true,
        "name": "cheapitem",
        "price": 0.5
    }'''

    # Expected Response Body
    expected_v1_products_POST_response_body = r'''{
        "detail": [
            {
                "loc": [
                    "body",
                    "price"
                ],
                "msg": "Value must be greater than or equal to 1.0",
                "type": "value_error.number.not_ge"
            }
        ]
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/products",
        method="POST",
        status_code=422,
        request_body=v1_products_POST_request_body,
        response_body=expected_v1_products_POST_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    v1_products_POST_response = client.send_request(
        url=URL,
        path="/api/v1/products",
        method="POST",
        body=v1_products_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert v1_products_POST_response.status_code == 422
    assert skyramp.check_schema(v1_products_POST_response, expected_v1_products_POST_response_body)
    assert skyramp.get_response_value(v1_products_POST_response, "detail.0.loc.0") is not None
    assert skyramp.get_response_value(v1_products_POST_response, "detail.0.msg") is not None
    assert skyramp.get_response_value(v1_products_POST_response, "detail.0.type") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_v_1_products_post()
