# Generated by Skyramp v1.2.14 on 2025-08-21 18:44:07.093244 -0700 PDT m=+0.544333501
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/products \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# Definition of authentication header
def get_header():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


# fuzz test for /api/v1/products GET
def test_products_get():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Fuzz strategies
    products_get_fuzzed_query = {
        "limit": -9,
        "offset": -10,
        "order": "JmTWfmi",
        "orderBy": "0123456789"
    }
    # Fuzz status codes
    expected_products_get_fuzzed_query_status_code = {
        "limit": "40x",
        "offset": "40x",
        "order": "40x",
        "orderBy": "40x"
    }

    # Execute Request
    products_GET_response = client.send_request(
        url=URL,
        path="/api/v1/products",
        method="GET",
        headers=headers,
        query_params={
            "limit": 10,
            "offset": 0,
            "order": "asc",
            "orderBy": None
        },
        expected_code="20x"
    )

    for key in products_get_fuzzed_query:
        query_params = {
            "limit": 10,
            "offset": 0,
            "order": "asc",
            "orderBy": None
        }

        query_params[key] = products_get_fuzzed_query[key]

        # Execute Request
        products_GET_response = client.send_request(
            url=URL,
            path="/api/v1/products",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_products_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { products_get_fuzzed_query[key] }'
        )

        query_params = {
            "limit": 10,
            "offset": 0,
            "order": "asc",
            "orderBy": None
        }

        query_params[key] = ""

        # Execute Request
        products_GET_response = client.send_request(
            url=URL,
            path="/api/v1/products",
            method="GET",
            headers=headers,
            query_params=query_params,
            expected_code=expected_products_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()




# fuzz test for /api/v1/products POST
def test_products_post():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Request Body
    products_POST_request_body = r'''{
            "category": "Toys",
            "description": "Bear Soft Toy",
            "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
            "in_stock": true,
            "name": "bigbear",
            "price": 9.99
        }'''
    
    # Fuzz strategies
    products_post_fuzzed_body = {
        "category": "0123456789",
        "description": "0123456789",
        "image_url": "0123456789",
        "in_stock": False,
        "name": "0123456789",
        "price": -10
    }
    # Fuzz status codes
    expected_products_post_status_code = {
        "category": "40x",
        "description": "40x",
        "image_url": "20x",
        "in_stock": "20x",
        "name": "40x",
        "price": "40x"
    }
    # Fuzz status codes for Null values
    expected_products_post_null_status_code = {
        "category": "40x",
        "description": "40x",
        "image_url": "40x",
        "in_stock": "40x",
        "name": "40x",
        "price": "40x"
    }

    # Execute Request
    products_POST_response = client.send_request(
        url=URL,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(products_post_fuzzed_body):
        # Execute Request
        products_POST_response = client.send_request(
            url=URL,
            path="/api/v1/products",
            method="POST",
            body=products_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(products_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_products_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(products_post_fuzzed_body, key) }'
        )

        # Execute Request
        products_POST_response = client.send_request(
            url=URL,
            path="/api/v1/products",
            method="POST",
            body=products_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_products_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()




# fuzz test for /api/v1/products/{product_id} GET
def test_products_product_id_get():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Declaration of variables
    product_id = 1

    # Execute Request
    products_product_id_GET_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="GET",
        headers=headers,
        path_params={"product_id": product_id},
        expected_code="20x"
    )

    assert client.is_success()




# fuzz test for /api/v1/products/{product_id} PUT
def test_products_product_id_put():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Declaration of variables
    product_id = 1

    # Request Body
    products_product_id_PUT_request_body = r'''{
            "category": "Toys",
            "description": "Bear Soft Toy",
            "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
            "in_stock": true,
            "name": "bigbear",
            "price": 29.99
        }'''
    
    # Fuzz strategies
    products_product_id_put_fuzzed_body = {
        "category": "0123456789",
        "description": "0123456789",
        "image_url": "0123456789",
        "in_stock": False,
        "name": "0123456789",
        "price": -10
    }
    # Fuzz status codes
    expected_products_product_id_put_status_code = {
        "category": "40x",
        "description": "40x",
        "image_url": "20x",
        "in_stock": "20x",
        "name": "40x",
        "price": "40x"
    }
    # Fuzz status codes for Null values
    expected_products_product_id_put_null_status_code = {
        "category": "40x",
        "description": "40x",
        "image_url": "40x",
        "in_stock": "40x",
        "name": "40x",
        "price": "40x"
    }

    # Execute Request
    products_product_id_PUT_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="PUT",
        body=products_product_id_PUT_request_body,
        headers=headers,
        path_params={"product_id": product_id},
        expected_code="20x"
    )

    for key in skyramp.iterate(products_product_id_put_fuzzed_body):
        # Execute Request
        products_product_id_PUT_response = client.send_request(
            url=URL,
            path="/api/v1/products/{product_id}",
            method="PUT",
            body=products_product_id_PUT_request_body,
            headers=headers,
            path_params={"product_id": product_id},
            data_override={key: skyramp.get_value(products_product_id_put_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_products_product_id_put_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(products_product_id_put_fuzzed_body, key) }'
        )

        # Execute Request
        products_product_id_PUT_response = client.send_request(
            url=URL,
            path="/api/v1/products/{product_id}",
            method="PUT",
            body=products_product_id_PUT_request_body,
            headers=headers,
            path_params={"product_id": product_id},
            data_override={key: None},
            expected_code=skyramp.get_value(expected_products_product_id_put_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()




# fuzz test for /api/v1/products/{product_id} DELETE
def test_products_product_id_delete():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Declaration of variables
    product_id = 1

    # Execute Request
    products_product_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="DELETE",
        headers=headers,
        path_params={"product_id": product_id},
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_products_get()
    test_products_post()
    test_products_product_id_get()
    test_products_product_id_put()
    test_products_product_id_delete()
