# Generated by Skyramp v1.2.14 on 2025-08-21 19:18:41.876519 -0700 PDT m=+0.717491959
# Command: skyramp generate contract rest http://localhost:8000/api/v1/products \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--query-params orderBy=created_at,order=desc \

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# Definition of authentication header
def get_header():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


# contract test for /api/v1/products GET
def test_products_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Expected Response Body
    expected_products_GET_response_body = r'''[
        {
            "category": "Toys",
            "created_at": "2025-02-25T10:54:22-05:00",
            "description": "Bear Soft Toy",
            "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
            "in_stock": true,
            "name": "bigbear",
            "price": 9.99,
            "product_id": 1,
            "updated_at": "2025-02-25T10:54:22-05:00"
        }
    ]'''

    # Execute Request
    products_GET_response = client.send_request(
        url=URL,
        path="/api/v1/products",
        method="GET",
        headers=headers,
        query_params={
            "limit": 10,
            "offset": 0,
            "order": "desc",
            "orderBy": "created_at"
        }
    )

    # Generated Assertions
    assert products_GET_response.status_code == 200
    assert skyramp.check_schema(products_GET_response, expected_products_GET_response_body)
    assert skyramp.get_response_value(products_GET_response, "0.category") is not None
    assert skyramp.get_response_value(products_GET_response, "0.created_at") is not None
    assert skyramp.get_response_value(products_GET_response, "0.description") is not None
    assert skyramp.get_response_value(products_GET_response, "0.stock_quantity") is not None



# contract test for /api/v1/products POST
def test_products_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Request Body
    products_POST_request_body = r'''{
        "category": "Toys",
        "description": "Bear Soft Toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear",
        "price": 9.99
    }'''

    # Expected Response Body
    expected_products_POST_response_body = r'''{
        "category": "Toys",
        "created_at": "2025-02-25T10:54:22-05:00",
        "description": "Bear Soft Toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear",
        "price": 9.99,
        "product_id": 1,
        "updated_at": "2025-02-25T10:54:22-05:00"
    }'''

    # Execute Request
    products_POST_response = client.send_request(
        url=URL,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers,
        query_params={
            "order": "desc",
            "orderBy": "created_at"
        }
    )

    # Generated Assertions
    assert products_POST_response.status_code == 201
    assert skyramp.check_schema(products_POST_response, expected_products_POST_response_body)
    assert skyramp.get_response_value(products_POST_response, "category") is not None
    assert skyramp.get_response_value(products_POST_response, "created_at") is not None
    assert skyramp.get_response_value(products_POST_response, "description") is not None
    assert skyramp.get_response_value(products_POST_response, "stock_quantity") is not None



# contract test for /api/v1/products/{product_id} GET
def test_products_product_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    product_id = 1

    # Expected Response Body
    expected_products_product_id_GET_response_body = r'''{
        "category": "Toys",
        "created_at": "2025-02-25T10:54:22-05:00",
        "description": "Bear Soft Toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear",
        "price": 9.99,
        "product_id": 1,
        "updated_at": "2025-02-25T10:54:22-05:00"
    }'''

    # Execute Request
    products_product_id_GET_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="GET",
        headers=headers,
        path_params={"product_id": product_id},
        query_params={
            "order": "desc",
            "orderBy": "created_at"
        }
    )

    # Generated Assertions
    assert products_product_id_GET_response.status_code == 200
    assert skyramp.check_schema(products_product_id_GET_response, expected_products_product_id_GET_response_body)
    assert skyramp.get_response_value(products_product_id_GET_response, "category") is not None
    assert skyramp.get_response_value(products_product_id_GET_response, "created_at") is not None
    assert skyramp.get_response_value(products_product_id_GET_response, "description") is not None
    assert skyramp.get_response_value(products_product_id_GET_response, "stock_quantity") is not None



# contract test for /api/v1/products/{product_id} PUT
def test_products_product_id_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    product_id = 1

    # Request Body
    products_product_id_PUT_request_body = r'''{
        "category": "Toys",
        "description": "Bear Soft Toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear",
        "price": 29.99
    }'''

    # Expected Response Body
    expected_products_product_id_PUT_response_body = r'''{
        "category": "Toys",
        "created_at": "2025-02-25T10:54:22-05:00",
        "description": "Bear Soft Toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear",
        "price": 29.99,
        "product_id": 1,
        "updated_at": "2025-02-25T10:54:22-05:00"
    }'''

    # Execute Request
    products_product_id_PUT_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="PUT",
        body=products_product_id_PUT_request_body,
        headers=headers,
        path_params={"product_id": product_id},
        query_params={
            "order": "desc",
            "orderBy": "created_at"
        }
    )

    # Generated Assertions
    assert products_product_id_PUT_response.status_code == 200
    assert skyramp.check_schema(products_product_id_PUT_response, expected_products_product_id_PUT_response_body)
    assert skyramp.get_response_value(products_product_id_PUT_response, "category") is not None
    assert skyramp.get_response_value(products_product_id_PUT_response, "created_at") is not None
    assert skyramp.get_response_value(products_product_id_PUT_response, "description") is not None
    assert skyramp.get_response_value(products_product_id_PUT_response, "stock_quantity") is not None



# contract test for /api/v1/products/{product_id} DELETE
def test_products_product_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    product_id = 1

    # Execute Request
    products_product_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="DELETE",
        headers=headers,
        path_params={"product_id": product_id},
        query_params={
            "order": "desc",
            "orderBy": "created_at"
        }
    )

    # Generated Assertions
    assert products_product_id_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_products_get()
    test_products_post()
    test_products_product_id_get()
    test_products_product_id_put()
    test_products_product_id_delete()
