# Generated by Skyramp v1.3.16 on 2026-03-30 02:42:29.99050827 +0000 UTC m=+296.188252824
# Command: skyramp generate contract rest http://localhost:8000/api/v1/products/{product_id} \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output products_min_price_put_contract_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python \
# 		--overwrite \
# 		--parent-request-data product_id={"category": "Toys", "description": "Bear Soft Toy", "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8", "in_stock": true, "name": "bigbear", "price": 9.99} \
# 		--parent-status-code product_id=201 \
# 		--request-data {"category":"Toys","description":"Bear Soft Toy","image_url":"https://images.app.goo.gl/cgcHpeehRdu5osot8","in_stock":true,"name":"bigbear","price":0.50} \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/products/{product_id} PUT
def test_api_v_1_products_product_id_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    product_id = 1

    # Request Body
    api_v1_products_product_id_PUT_request_body = r'''{
        "category": "Toys",
        "description": "Bear Soft Toy",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "bigbear",
        "price": 0.5
    }'''

    # Expected Response Body
    expected_api_v1_products_product_id_PUT_response_body = r'''{
        "detail": [
            {
                "field": "price",
                "message": "Input should be greater than or equal to 1",
                "type": "greater_than_equal"
            }
        ]
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="PUT",
        status_code=400,
        request_body=api_v1_products_product_id_PUT_request_body,
        response_body=expected_api_v1_products_product_id_PUT_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    api_v1_products_product_id_PUT_response = client.send_request(
        url=URL,
        path="/api/v1/products/{product_id}",
        method="PUT",
        body=api_v1_products_product_id_PUT_request_body,
        headers=headers,
        path_params={"product_id": product_id}
    )

    # Generated Assertions
    assert api_v1_products_product_id_PUT_response.status_code == 400
    assert skyramp.check_schema(api_v1_products_product_id_PUT_response, expected_api_v1_products_product_id_PUT_response_body)
    assert skyramp.get_response_value(api_v1_products_product_id_PUT_response, "detail.0.field") is not None
    assert skyramp.get_response_value(api_v1_products_product_id_PUT_response, "detail.0.message") is not None
    assert skyramp.get_response_value(api_v1_products_product_id_PUT_response, "detail.0.type") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_api_v_1_products_product_id_put()
