# Generated by Skyramp v1.2.20 on 2025-09-16 15:17:36.293089 -0700 PDT m=+0.844492792
# Command: skyramp generate contract rest http://localhost:8000/api/v1/reset \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--framework pytest \
# 		--language python \

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /api/v1/reset POST
def test_reset_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    # expected_reset_POST_response_body = r'''"string"'''

    # Execute Request
    reset_POST_response = client.send_request(
        url=URL,
        path="/api/v1/reset",
        method="POST",
        headers=headers
    )

    # Generated Assertions
    assert reset_POST_response.status_code == 200
    # assert skyramp.check_schema(reset_POST_response, expected_reset_POST_response_body)

if __name__ == "__main__":
    test_reset_post()
