# Generated by Skyramp v1.3.16 on 2026-03-29 02:07:12.86939194 +0000 UTC m=+322.607483130
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output products_min_price_contract_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/scenario_product_min_price_validation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    products_POST_request_body = r'''{
        "category": "Toys",
        "description": "Test product",
        "image_url": "https://images.app.goo.gl/cgcHpeehRdu5osot8",
        "in_stock": true,
        "name": "testproduct",
        "price": 0.5
    }'''
    
    # Execute Request
    products_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/products",
        method="POST",
        body=products_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert products_POST_response.status_code == 400
    assert skyramp.get_response_value(products_POST_response, "detail.0.field") is not None
    assert skyramp.get_response_value(products_POST_response, "detail.0.message") is not None
    assert skyramp.get_response_value(products_POST_response, "detail.0.type") is not None


if __name__ == "__main__":
    test_integration()
