// Generated by Skyramp v1.3.16 on 2026-03-30 04:17:01.42103129 +0000 UTC m=+339.654672521
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add_different_product_after_warning.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/add_different_product_after_warning_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(326000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Amazon Echo Dot").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Amazon Echo Dot").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await expect(page.getByTestId("add-order-product-name-Amazon Echo Dot")).toContainText("Amazon Echo Dot");
    await expect(page.getByTestId("add-order-product-quantity-Amazon Echo Dot")).toContainText("x1");
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("customer@test.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Nike T-shirt").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Nike T-shirt").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Rayban Sunglasses").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await expect(page.getByTestId("add-order-product-name-Nike T-shirt")).toContainText("Nike T-shirt");
    await expect(page.getByTestId("add-order-product-name-Rayban Sunglasses")).toContainText("Rayban Sunglasses");
});
