// Generated by Skyramp v1.3.16 on 2026-03-29 02:09:17.610066731 +0000 UTC m=+212.476262926
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add_product_price_validation.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/add_product_price_validation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(213000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Apple MacBook Air").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByTestId("add-order-product-quantity-Apple MacBook Air").fill("3");
    await page.goto("http://localhost:5173/products");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Test Product");
    await page.getByTestId("new_product_price").fill("0.50");
    await page.getByTestId("new_product_price").fill("9.99");
});
