// Generated by Skyramp v1.3.16 on 2026-03-29 16:22:48.298889357 +0000 UTC m=+271.397662845
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output autosave_status_indicator_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/autosave_status_indicator_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(325000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://demoshop.skyramp.dev/products");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    await page.getByTestId("product-detail-input-name").click();
    await page.getByTestId("product-detail-input-name").fill(" Updated");
    await page.getByTestId("product-detail-input-description").click();
    await page.keyboard.press("End");
    await page.keyboard.press("!");
    await page.getByRole("button", { name: "Back" }).click();
});
