// Generated by Skyramp v1.3.16 on 2026-03-30 03:10:20.308976149 +0000 UTC m=+337.443584188
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cancel_order_modal_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/cancel_order_modal_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(485000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-def@mail.com - 2 items").getByRole("button", { name: "View details for order 1" }).click();
    await page.getByRole("button", { name: "Cancel Order" }).click();
    await page.goto("http://localhost:5173/orders/12");
    await expect(page.getByTestId("order-detail-heading")).toContainText("Order Details");
    await page.getByRole("button", { name: "Cancel Order" }).click();
});
