// Generated by Skyramp v1.3.16 on 2026-03-29 15:36:19.429904163 +0000 UTC m=+218.792149998
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cancel_order_backdrop_bug.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/cancel_order_backdrop_bug_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(150000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React/framework hydration to complete
    await page.waitForTimeout(1500);
    await page.goto("http://localhost:5173/orders/2");
    // Wait for React/framework hydration to complete
    await page.waitForTimeout(1500);
    await page.getByTestId("cancel-order-trigger").click();
    // Wait for modal to fully render
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/orders/**");
    await page.keyboard.press("Escape");
    const response0 = await responsePromise0;
});
