// Generated by Skyramp v1.3.16 on 2026-03-29 03:21:34.141320708 +0000 UTC m=+422.029758520
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output confirm_cancel_order.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/confirm_cancel_order_v2_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(651000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/orders/8");
    // Wait for React/framework hydration to complete
    await page.waitForTimeout(1500);
    await page.getByTestId("cancel-order-trigger").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/orders/**");
    await page.getByTestId("cancel-order-button").click();
    const response0 = await responsePromise0;
});
