// Generated by Skyramp v1.3.16 on 2026-03-30 04:05:54.653345963 +0000 UTC m=+189.529440195
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output duplicate_product_warning.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/duplicate_product_warning_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

async function openAddOrderForm(page, email) {
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill(email);
}

async function selectAndAddAdidasRunningShoes(page) {
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Adidas Running Shoes").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
}

test('testUi', async ({ page }) => {
    test.setTimeout(215000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await openAddOrderForm(page, "test@example.com");
    await selectAndAddAdidasRunningShoes(page);
    await selectAndAddAdidasRunningShoes(page);
    // Assert warning appears when duplicate product is attempted
    await expect(page.getByTestId("add-order-duplicate-warning")).toBeVisible();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await expect(page.getByTestId("add-order-product-name-Adidas Running Shoes")).toContainText("Adidas Running Shoes");
    await expect(page.getByTestId("add-order-product-quantity-Adidas Running Shoes")).toContainText("x1");
});
