// Generated by Skyramp v1.3.16 on 2026-03-30 18:08:31.813294428 +0000 UTC m=+459.855721397
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_form.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/edit_order_form_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(149000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-def@mail.com - 2 items").getByRole("button", { name: "View details for order 1" }).click();
    await page.getByTestId("order-detail-edit-btn").click();
    await expect(page.getByTestId("edit-order-input-email")).toHaveValue("def@mail.com");
    await page.getByTestId("edit-order-input-email").fill("edited@example.com");
    await expect(page.getByTestId("edit-order-input-email")).toHaveValue("edited@example.com");
    await page.getByTestId("edit-order-discount-type-trigger").click();
    await page.getByTestId("edit-order-discount-type-percentage").click();
    await page.getByTestId("edit-order-discount-value-input").fill("20");
    await expect(page.getByTestId("edit-order-total")).toContainText("$799.98");
});
