// Generated by Skyramp v1.3.16 on 2026-03-29 01:16:00.736301524 +0000 UTC m=+185.823861209
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_upload_validation_tests.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/image_validation_trace.zip

// Import of required libraries
import { test, expect } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// Test #1: File type validation - upload a non-image file and verify rejection
test('ui-file-type-validation', async ({ page }) => {
    test.setTimeout(60000);
    page.setDefaultTimeout(pageTimeout);
    const rawPage = page;
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React hydration to complete
    await page.waitForTimeout(1500);
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Validation Test Product");

    // Upload a text file (non-image) using setInputFiles
    await rawPage.locator('input[type="file"]').setInputFiles({
        name: 'test-document.txt',
        mimeType: 'text/plain',
        buffer: Buffer.from('This is a text file, not an image'),
    });

    // Assert that an error message is shown for invalid file type
    await expect(rawPage.getByTestId('upload-error')).toBeVisible();
    await expect(rawPage.getByTestId('upload-error')).toContainText(/invalid file type|only jpg|only png|only webp|jpeg|png|webp/i);
});

// Test #2: File size validation - upload a file over 5MB and verify rejection
test('ui-file-size-validation', async ({ page }) => {
    test.setTimeout(60000);
    page.setDefaultTimeout(pageTimeout);
    const rawPage = page;
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React hydration to complete
    await page.waitForTimeout(1500);
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Size Validation Test Product");

    // Create a buffer larger than 5MB (5 * 1024 * 1024 + 1 = 5,242,881 bytes)
    const oversizedBuffer = Buffer.alloc(5 * 1024 * 1024 + 1, 0xff);
    await rawPage.locator('input[type="file"]').setInputFiles({
        name: 'large-image.jpg',
        mimeType: 'image/jpeg',
        buffer: oversizedBuffer,
    });

    // Assert that an error message is shown for file size exceeding 5MB
    await expect(rawPage.getByTestId('upload-error')).toBeVisible();
    await expect(rawPage.getByTestId('upload-error')).toContainText(/too large|exceeds|5mb|5 mb|size limit/i);
});

// Test #5: File size display format - verify size is shown in KB/MB not raw bytes
test('ui-file-size-display-format', async ({ page }) => {
    test.setTimeout(60000);
    page.setDefaultTimeout(pageTimeout);
    const rawPage = page;
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React hydration to complete
    await page.waitForTimeout(1500);
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Display Format Test Product");

    // Upload a valid small JPEG image (about 100KB)
    const imageBuffer = Buffer.alloc(100 * 1024, 0xff);
    await rawPage.locator('input[type="file"]').setInputFiles({
        name: 'test-image.jpg',
        mimeType: 'image/jpeg',
        buffer: imageBuffer,
    });

    // Wait for image info to appear after successful upload
    await expect(rawPage.getByTestId('image-info')).toBeVisible();

    // Assert that file size is displayed in KB or MB format, NOT raw bytes
    const fileSizeText = await rawPage.getByTestId('file-size').textContent();
    expect(fileSizeText).toMatch(/KB|MB/);
    expect(fileSizeText).not.toMatch(/\d+ bytes$/);
});

// Test #10: GIF file rejection - verify GIF files are not accepted
test('ui-gif-file-rejection', async ({ page }) => {
    test.setTimeout(60000);
    page.setDefaultTimeout(pageTimeout);
    const rawPage = page;
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React hydration to complete
    await page.waitForTimeout(1500);
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("GIF Rejection Test Product");

    // Upload a GIF file (should be rejected - only JPG, PNG, WEBP allowed)
    const gifHeader = Buffer.from('GIF89a\x01\x00\x01\x00\x80\x00\x00\xff\xff\xff\x00\x00\x00!\xf9\x04\x00\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;');
    await rawPage.locator('input[type="file"]').setInputFiles({
        name: 'animated.gif',
        mimeType: 'image/gif',
        buffer: gifHeader,
    });

    // Assert that an error message is shown for GIF files
    await expect(rawPage.getByTestId('upload-error')).toBeVisible();
    await expect(rawPage.getByTestId('upload-error')).toContainText(/gif|invalid file type|not supported|only jpg|only png|only webp/i);
});
