// Generated by Skyramp v1.3.16 on 2026-03-29 03:17:20.222786231 +0000 UTC m=+182.691796211
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_upload_choose_file_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/image_upload_remove_btn_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(96000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Remove Image Test Product");
    await page.getByTestId("new_product_description").fill("Testing the remove image functionality");
    await page.getByTestId("new_product_category").fill("Electronics");
    await page.getByTestId("new_product_price").click();
    await page.getByTestId("new_product_price").fill("49.99");
    await page.getByTestId("upload-button").click();
});
