// Generated by Skyramp v1.3.16 on 2026-03-30 04:10:14.843024646 +0000 UTC m=+251.369678934
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_upload_label_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/image_label_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(299000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/products");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("SkyPhone Pro");
    await page.getByTestId("new_product_description").fill("A premium smartphone with advanced features");
    await expect(page.getByTestId("new_product_image_upload_btn")).toContainText("Click to upload image");
    await page.getByTestId("new_product_category").fill("Electronics");
    await page.getByRole("combobox").click();
    await page.getByTestId("new_product_instock_yes").click();
    await page.getByTestId("new_product_price").fill("599.99");
    await expect(page.getByTestId("new_product_image_upload_btn")).toContainText("JPG, PNG, WEBP");
    await page.getByRole("button", { name: "Submit" }).click();
    await expect(page.getByRole("button", { name: "Submit" })).toContainText("Submit");
    await page.goto("http://localhost:5173/products");
    await page.getByRole("button", { name: "Add Product" }).click();
    await expect(page.getByTestId("add-product-label-image")).toContainText("Product Image");
    await expect(page.getByTestId("new_product_image_upload_btn")).toContainText("JPG, PNG, WEBP — max 5 MB");
    await page.getByTestId("add-product-modal-close").click();
    await expect(page.getByTestId("product-catalog-heading")).toContainText("Product Catalog");
});
