// Generated by Skyramp v1.3.16 on 2026-03-30 04:00:07.852010721 +0000 UTC m=+178.687636885
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output image_upload_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/image_upload_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(175000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByRole("button", { name: "Add Product" }).click();

    const playwrightRequest0: Record<string, any> = {
        "category": "Electronics",
        "description": "A test product for image upload validation",
        "name": "Test Product Upload",
        "price": 49.99
    };

    await page.getByTestId("new_product_name").fill(getValue(playwrightRequest0, "name"));
    await page.getByTestId("new_product_description").fill(getValue(playwrightRequest0, "description"));
    await expect(page.getByTestId("new_product_image_upload_btn")).toContainText("Click to upload image");
    await expect(page.getByTestId("new_product_image_upload_btn")).toContainText("JPG, PNG, WEBP");
    await page.getByTestId("new_product_category").fill(getValue(playwrightRequest0, "category"));
    await page.getByTestId("new_product_price").fill(getValue(playwrightRequest0, "price").toString());
    await page.getByRole("combobox").click();
    await page.getByTestId("new_product_instock_yes").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("button", { name: "Submit" })).toContainText("Submit");
});
