// Generated by Skyramp v1.3.16 on 2026-03-30 02:42:56.388711643 +0000 UTC m=+163.948431543
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_quantity_summary_ui.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/order_quantity_summary_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(155000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Apple iPhone 16").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await expect(page.getByTestId("add-order-summary-subtotal")).toContainText("$799.99");
    await expect(page.getByText("$879.99")).toContainText("$879.99");
    await page.getByTestId("add-order-product-quantity-input-Apple iPhone 16").fill("2");
    await expect(page.getByTestId("add-order-product-quantity-input-Apple iPhone 16")).toHaveValue("2");
    await expect(page.getByTestId("add-order-summary-subtotal")).toContainText("$1599.98");
    await expect(page.getByText("$1759.98")).toContainText("$1759.98");
});
