// Generated by Skyramp v1.3.16 on 2026-03-29 03:24:44.436012783 +0000 UTC m=+290.632930062
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_summary_item_delete_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/order_summary_delete_item_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(405000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("summary-test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Samsung Galaxy Buds").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByTestId("add-order-product-quantity-Samsung Galaxy Buds").dblclick();
    await page.getByTestId("add-order-product-quantity-Samsung Galaxy Buds").fill("2");
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("multi-product@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Google Nest Mini").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Amazon Echo Dot").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("delete-test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Amazon Echo Dot").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByTestId("add-order-product-delete-btn-Amazon Echo Dot").click();
});
