// Generated by Skyramp v1.3.16 on 2026-03-30 19:26:23.931069496 +0000 UTC m=+320.551191580
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output order_stock_validation.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/order_stock_validation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(354000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("product-Google-Pixel-4-stock-badge").waitFor({ state: 'visible', timeout: 15000 });
    await expect(page.getByTestId("product-Google-Pixel-4-stock-badge")).toContainText("In Stock");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await expect(page.getByTestId("product-detail-value-stockquantity")).toContainText("60 units");
    await expect(page.getByTestId("product-detail-value-instock")).toContainText("In Stock");
    await page.goto("http://localhost:5173/products");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.getByTestId("new_product_name").fill("Test Stock Product");
    await page.getByTestId("new_product_stock_quantity").fill("25");
    await expect(page.getByTestId("new_product_stock_quantity")).toHaveValue("25");
    await expect(page.getByTestId("new_product_name")).toHaveValue("Test Stock Product");
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("test@example.com");
    await page.getByRole("combobox").click();
    await expect(page.getByTestId("add-order-product-option-Google Pixel 4")).toContainText("60 left");
    await page.getByTestId("add-order-product-option-Google Pixel 4").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await expect(page.getByTestId("add-order-product-name-Google Pixel 4")).toContainText("Google Pixel 4");
});
