// Generated by Skyramp v1.3.16 on 2026-03-30 04:42:54.627151664 +0000 UTC m=+264.569041859
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pagination_session_nav_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/pagination_session_navigation_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(261000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/products");
    await page.getByRole("button", { name: "Edit Session ID" }).click();
    await page.getByRole("textbox").fill("skyramp-ui-test");
    await page.getByRole("button", { name: "Save Session ID" }).click();
    await expect(page.getByTestId("product-catalog-heading")).toContainText("Product Catalog");
    await page.getByTestId("navbar-orders").click();
    await expect(page.getByTestId("order-catalog-heading")).toContainText("Order Catalog");
    await page.getByTestId("navbar-products").click();
});
