// Generated by Skyramp v1.3.16 on 2026-03-29 03:19:39.568165807 +0000 UTC m=+217.355333291
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_autosave_description_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/autosave_description_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(255000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    await page.getByTestId("product-detail-input-name").fill("Google Pixel 4 Pro");
    await page.getByTestId("product-detail-input-price").click();
    await page.getByTestId("product-detail-input-price").fill("899.99");
    await page.goto("http://localhost:5173/products");
    await page.getByTestId("product-Apple-MacBook-Air-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();

    const playwrightRequest0: Record<string, any> = {"description": "The thinnest and lightest MacBook ever - now with M3 chip."};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-description").fill(getValue(playwrightRequest0, "description"));
    const response0 = await responsePromise0;

    // Assert autosave status indicator shows "Saving..." after description edit
    await expect(page.getByTestId("autosave-status")).toContainText("Saving...");
    // Assert auto-save PUT request for description change succeeded
    expect(response0.status(), 'auto-save description response status').toBe(200);
});
