// Generated by Skyramp v1.3.16 on 2026-03-29 03:22:55.594648095 +0000 UTC m=+154.825705390
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_clear_filters_bug.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/clear_filters_bug_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(82000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/products");
    await page.getByRole("textbox", { name: "Search products..." }).fill("Apple");
    await page.getByRole("combobox").click();
    await page.getByRole("option", { name: "laptop" }).click();
    await page.getByRole("button", { name: "Clear Filters" }).click();
    await page.getByRole("textbox", { name: "Search products..." }).fill("xyznonexistent");
    await page.getByRole("button", { name: "Clear Filters" }).click();
});
