// Generated by Skyramp v1.3.16 on 2026-03-30 04:17:07.02017924 +0000 UTC m=+162.717452206
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_sort_desc_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/sort_desc_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(165000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("sort-select").click();
    await page.getByRole("option", { name: "Name: Z-A" }).click();
    await expect(page.getByTestId("product-Rayban-Sunglasses")).toContainText("Rayban Sunglasses");
    await page.getByTestId("sort-select").click();
    await page.getByRole("option", { name: "Price: High to Low" }).click();
    await expect(page.getByTestId("product-Rayban-Sunglasses-price")).toContainText("$99.99");
});
