// Generated by Skyramp v1.3.16 on 2026-03-29 02:37:11.926257098 +0000 UTC m=+98.434152188
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_list_pagination.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_list_pagination_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("product-list-page-size-top").click();
    await page.getByTestId("product-list-page-size-top").selectOption("10");
    await page.getByTestId("product-list-next-top").click();
    await page.getByTestId("product-list-prev-top").click();
});
