// Generated by Skyramp v1.3.16 on 2026-03-29 00:52:17.300219093 +0000 UTC m=+110.746860144
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_detail_autosave_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_detail_autosave_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(76000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByRole("button", { name: "Add Product" }).click();
    await page.goto("http://localhost:5173/products/add");
    await page.goto("http://localhost:5173/products");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();

    const playwrightRequest0: Record<string, any> = {"name": " Updated"};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-name").fill(getValue(playwrightRequest0, "name"));
    const response0 = await responsePromise0;
});
