// Generated by Skyramp v1.3.16 on 2026-03-30 04:44:26.585481024 +0000 UTC m=+369.513167698
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_autosave_name_desc.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_autosave_save_status_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(297000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for the page to fully load and hydrate before interacting
    await page.waitForLoadState('networkidle');
    // Wait for a visible product card to confirm products have loaded
    await page.locator('[data-testid$="-view-details"]').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.locator('[data-testid$="-view-details"]').first().click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    await page.getByTestId("product-detail-input-name").click();

    const playwrightRequest0: Record<string, any> = {"name": "Auto Save Test - Name Updated"};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-name").fill(getValue(playwrightRequest0, "name"));
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("product-detail-input-name")).toHaveValue("Auto Save Test - Name Updated");
    await page.getByTestId("product-detail-input-description").click();

    const playwrightRequest1: Record<string, any> = {"description": "Auto-save description test."};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-description").fill(getValue(playwrightRequest1, "description"));
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const responsePromise2 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Save Product" }).click();
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("product-detail-value-name")).toContainText("Auto Save Test - Name Updated");
    await expect(page.getByTestId("product-detail-value-description")).toContainText("Auto-save description test");
});
