// Generated by Skyramp v1.3.16 on 2026-03-29 02:12:11.525237695 +0000 UTC m=+156.935924269
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_category_filter.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_category_filter_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(186000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("product-list-search").fill("Apple");
    await page.getByTestId("product-list-category-filter").selectOption("mobile");
    await page.getByTestId("product-list-clear-filters").click();
    await page.goto("http://localhost:5173/products");
    await page.getByTestId("product-list-category-filter").selectOption("headphones");
    await page.getByTestId("product-list-clear-filters").click();
});
