// Generated by Skyramp v1.3.16 on 2026-03-30 04:44:34.899843091 +0000 UTC m=+377.827529755
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_autosave_stock_status.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_autosave_stock_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(527000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for the page to fully load and hydrate before interacting
    await page.waitForLoadState('networkidle');
    // Wait for a visible product card to confirm products have loaded
    await page.locator('[data-testid$="-view-details"]').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.locator('[data-testid$="-view-details"]').first().click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-instock").selectOption("false");
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const responsePromise1 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Save Product" }).click();
    const response1 = await responsePromise1;

    await expect(page.getByTestId("product-detail-value-outstock")).toContainText("Out of Stock");
});
