// Generated by Skyramp v1.3.16 on 2026-03-29 15:37:21.151494575 +0000 UTC m=+161.388246475
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_autosave_saved_status_never_appears_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/autosave_saved_status_never_appears_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for React/framework hydration to complete
    await page.waitForTimeout(1500);
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    await page.getByTestId("product-detail-input-name").click();

    const playwrightRequest0: Record<string, any> = {"name": "Google Pixel 4 Updated"};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-name").fill(getValue(playwrightRequest0, "name"));
    const response0 = await responsePromise0;
});
