// Generated by Skyramp v1.3.16 on 2026-03-30 04:32:22.275489825 +0000 UTC m=+314.178871792
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_edit_autosave.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_edit_autosave_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(428000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    // Wait for the page to fully load and hydrate before interacting
    await page.waitForLoadState('networkidle');
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();

    const playwrightRequest0: Record<string, any> = {"name": " Updated"};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-name").fill(getValue(playwrightRequest0, "name"));
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("product-detail-input-name")).toHaveValue("Updated");

    const playwrightRequest1: Record<string, any> = {"name": "Google Pixel 4 Test"};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-name").fill(getValue(playwrightRequest1, "name"));
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("product-detail-input-description").click();

    const playwrightRequest2: Record<string, any> = {"description": "Capture stunning photos with the Google Pixel 4. Auto-save test."};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-description").fill(getValue(playwrightRequest2, "description"));
    const response2 = await responsePromise2;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const responsePromise3 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Save Product" }).click();
    const response3 = await responsePromise3;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByTestId("product-detail-value-name")).toContainText("Google Pixel 4 Test");
    await expect(page.getByTestId("product-detail-value-description")).toContainText("Auto-save test");
});
