// Generated by Skyramp v1.3.16 on 2026-03-30 04:11:38.963271419 +0000 UTC m=+132.566668733
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_sort_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/product_sort_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(101000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("sort-select").click();
    await page.getByRole("option", { name: "Price: Low to High" }).click();
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId("product-Nike-T-shirt")).toContainText("Nike T-shirt");
    await page.getByTestId("sort-select").click();
    await page.getByRole("option", { name: "Name: A-Z" }).click();
    await expect(page.getByTestId("product-Adidas-Running-Shoes")).toContainText("Adidas Running Shoes");
});
