// Generated by Skyramp v1.3.16 on 2026-03-29 03:18:04.64942362 +0000 UTC m=+122.436591104
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_autosave_status_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/autosave_status_ui_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.getByRole("button", { name: "Edit Product" }).click();

    const playwrightRequest0: Record<string, any> = {"name": "Google Pixel 4 Pro"};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-name").fill(getValue(playwrightRequest0, "name"));
    const response0 = await responsePromise0;

    // Assert autosave status indicator appears with "Saving..." text
    await expect(page.getByTestId("autosave-status")).toContainText("Saving...");
    // Assert auto-save PUT request succeeded
    expect(response0.status(), 'auto-save response status').toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("product-detail-input-price").click();

    const playwrightRequest1: Record<string, any> = {"price": 899.99};

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/products/**");
    await page.getByTestId("product-detail-input-price").fill(getValue(playwrightRequest1, "price").toString());
    const response1 = await responsePromise1;

    // Assert auto-save PUT request for price change succeeded
    expect(response1.status(), 'auto-save price response status').toBe(200);
});
