// Generated by Skyramp v1.3.16 on 2026-03-30 03:45:16.603832671 +0000 UTC m=+169.162185365
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output review_form_product_detail.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/review_form_star_rating_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(201000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await page.goto("http://localhost:5173/products/23");
    await page.goto("http://localhost:5173/products");
    await expect(page.getByTestId("product-catalog-heading")).toContainText("Product Catalog");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await expect(page.getByTestId("product-detail-heading")).toContainText("Product Details");
    await expect(page.getByTestId("product-detail-value-name")).toContainText("Google Pixel 4");
});
