// Generated by Skyramp v1.3.16 on 2026-03-29 03:20:02.082929208 +0000 UTC m=+270.466207234
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sort_e2e_workflow_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/public/traces/e2e_test_playwright.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(263000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("https://demoshop.skyramp.dev/products");
    await page.getByRole("button", { name: "Edit Session ID" }).click();
    await page.getByRole("textbox").click();
    await page.getByRole("textbox").fill("softly-savepopular");
    await page.getByRole("textbox").press("ArrowUp");
    await page.getByRole("textbox").fill("popular");
    await page.getByRole("textbox").press("ArrowDown");
    await page.getByRole("textbox").fill("skyramp-e2e-demo");
    await page.getByRole("button", { name: "Save Session ID" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/reset**");
    await page.getByTestId("navbar-clear-state").click();
    const response0 = await responsePromise0;

    await page.getByRole("button", { name: "Copy Session ID" }).click();
    await page.goto("https://demoshop.skyramp.dev/products");
    await page.getByTestId("product-SkyPad-Pro-view-details").click();
    await page.getByTestId("product-detail-root").click();
    await page.getByRole("button", { name: "Edit Product" }).click();
    await page.getByTestId("product-detail-input-price").click();
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");
    await page.getByTestId("product-detail-input-price").press("ArrowLeft");

    const playwrightRequest0: Record<string, any> = {"price": 1999.99};

    await page.getByTestId("product-detail-input-price").fill(getValue(playwrightRequest0, "price").toString());
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Save Product" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-sahil@skyramp.dev - 1 items").getByTestId("order-view-details-btn").click();
    await expect(page.getByTestId("order-detail-value-total")).toContainText("$3999.98");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v1/orders/**");
    await page.getByRole("button", { name: "Cancel Order" }).click();
    const response2 = await responsePromise2;

    await page.getByTestId("navbar-products").click();
    await page.getByTestId("product-SkyPad-Pro-view-details").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise3 = page.waitForResponse("**/api/v1/products/**");
    await page.getByRole("button", { name: "Delete Product" }).click();
    const response3 = await responsePromise3;
});
