// Generated by Skyramp v1.3.16 on 2026-03-29 03:19:29.523232256 +0000 UTC m=+237.906510272
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sort_price_navigate_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/sort_price_navigate_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(203000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("sort-select").selectOption("name-asc");
    await page.getByTestId("sort-select").selectOption("name-desc");
    await page.getByTestId("sort-select").selectOption("date-newest");
    await page.getByTestId("sort-select").selectOption("date-oldest");
    await page.getByTestId("sort-select").selectOption("default");
    await page.goto("http://localhost:5173/products");
    await page.getByTestId("sort-select").selectOption("price-low-high");
    await page.getByTestId("product-Nike-T-shirt-view-details").click();
    await page.getByRole("button", { name: "Back" }).click();
});
