// Generated by Skyramp v1.3.16 on 2026-03-29 00:54:19.488948625 +0000 UTC m=+111.110847319
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sort_products_ui_test.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/sort_products_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(84000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("sort-select").selectOption("price-low-high");
    await page.getByTestId("sort-select").selectOption("price-high-low");
    await page.getByTestId("sort-select").selectOption("default");
});
