// Generated by Skyramp v1.3.16 on 2026-03-30 19:24:23.76532931 +0000 UTC m=+200.385451394
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output stock_status_display.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/stock_status_display_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(72000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("product-Google-Pixel-4-stock-badge").waitFor({ state: 'visible', timeout: 15000 });
    await expect(page.getByTestId("product-Google-Pixel-4-stock-badge")).toContainText("In Stock");
    await page.getByTestId("product-Google-Pixel-4-view-details").click();
    await expect(page.getByTestId("product-detail-value-stockquantity")).toContainText("60 units");
    await expect(page.getByTestId("product-detail-value-instock")).toContainText("In Stock");
});
