// Generated by Skyramp v1.3.16 on 2026-03-29 03:19:31.781824634 +0000 UTC m=+246.522111560
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_duplicate_warning_assertion.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/duplicate_warning_v2_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(186000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByRole("button", { name: "Next" }).first().click();
    await page.getByRole("button", { name: "Previous" }).first().click();
    await page.getByLabel("Items per page:").selectOption("25");
    await page.goto("http://localhost:5173/orders");
    await page.getByTestId("add-order-btn").click();
    await page.getByTestId("add-order-input-email").fill("test@example.com");
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Apple MacBook Air").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
    await page.getByRole("combobox").click();
    await page.getByTestId("add-order-product-option-Apple MacBook Air").click();
    await page.getByTestId("add-order-products-container").getByRole("button", { name: "Add" }).click();
});
