// Generated by Skyramp v1.3.16 on 2026-03-29 16:18:29.223657935 +0000 UTC m=+100.624631853
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_modal_escape_key_handling.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/ui_modal_escape_key_handling_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.getByTestId("navbar-orders").click();
    await page.getByTestId("order-klm@mail.com - 2 items").getByTestId("order-view-details-btn").click();
    await page.getByTestId("cancel-order-trigger").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v1/orders/**");
    await page.press("Escape");
    const response0 = await responsePromise0;
});
